# coding: utf-8

"""
    SDX-Controller

    You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).   # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: yxin@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.connection_v2_endpoints import \
    ConnectionV2Endpoints  # noqa: E501
from swagger_client.rest import ApiException


class TestConnectionV2Endpoints(unittest.TestCase):
    """ConnectionV2Endpoints unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectionV2Endpoints(self):
        """Test ConnectionV2Endpoints"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.connection_v2_endpoints.ConnectionV2Endpoints()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
